Repository GrEFeRFeeD/intellistart-java-2022-oneweek, pull requests merged in 2022-10, with the labels that each got.

#14 :sparkles: Implement getCurrentUser() method.
  src/main/java/com/intellias/intellistart/interviewplanning/model/user/UserService.java
Labels: feature

#15 :recycle: Refactor BookingLimit: make entity M:N for User and Week in…
  src/main/java/com/intellias/intellistart/interviewplanning/initialization/StartDataLoader.java
  src/main/java/com/intellias/intellistart/interviewplanning/model/booking/Booking.java
  src/main/java/com/intellias/intellistart/interviewplanning/model/booking/BookingKey.java
  src/main/java/com/intellias/intellistart/interviewplanning/model/bookinglimit/BookingLimit.java
  src/main/java/com/intellias/intellistart/interviewplanning/model/bookinglimit/BookingLimitKey.java
  src/main/java/com/intellias/intellistart/interviewplanning/model/bookinglimit/BookingLimitRepository.java
  src/main/java/com/intellias/intellistart/interviewplanning/model/interviewerslot/InterviewerSlot.java
  src/main/java/com/intellias/intellistart/interviewplanning/model/user/User.java
  src/main/java/com/intellias/intellistart/interviewplanning/model/user/UserService.java
  src/main/java/com/intellias/intellistart/interviewplanning/model/week/Week.java
Labels: enhancement

#16 ♻️Refactor getCurrentUser() plug-method
  src/main/java/com/intellias/intellistart/interviewplanning/model/user/UserService.java
Labels: bug

#37 :hammer: Fix CandidateSlotValidator.validateOverlapping
  src/main/java/com/intellias/intellistart/interviewplanning/model/candidateslot/validation/CandidateSlotValidator.java
Labels: bug
